// frontend/src/components/job/job.vue
<template>
  <v-layout column>
    <v-container fluid class="content-container">
      <v-layout row wrap justify-center>
        <v-flex sm10 xs12 mt-5 v-if="!loading">
          <v-card flat class="mb-4">
            <v-card-text>
              <h3 class="title mb-4">Title</h3>
              <p class="mb-4">{{job.title}}</p>
              <h3 class="title mb-4">Salary - Benefits</h3>
              <p class="mb-4">{{job.salary}} - {{job.benefits}}</p>
              <h3 class="title mb-4">Type</h3>
              <p class="mb-4">{{job.jobType}}</p>
              <h3 class="title mb-4">Location</h3>
              <p class="mb-4">{{job.jobLocation}}</p>
              <h3 class="title mb-4">Reference</h3>
              <p class="mb-4">{{job.jobReference}}</p>
              <div v-html="job.description"></div>
            </v-card-text>
          </v-card>
          <v-layout justify-center content-subtitle mt-2 mb-4>
            <v-btn depressed color="primary" to="/jobs">Jobs</v-btn>
          </v-layout>
        </v-flex>
        <v-flex md8 sm10 xs12 mt-5 mb-5 text-xs-center v-if="loading">
           <v-progress-circular indeterminate color="primary"></v-progress-circular>
        </v-flex>
      </v-layout>
    </v-container>
  </v-layout>
</template>
<script src="./job.ts"></script>

// frontend/src/components/Pages/Job.tsx
import React, { FunctionComponent, useState, useEffect } from "react";
import { Link, withRouter, RouteComponentProps } from "react-router-dom";
import { createStyles, Theme, makeStyles } from "@material-ui/core/styles";
import Grid from "@material-ui/core/Grid";
import CircularProgress from "@material-ui/core/CircularProgress";
import Button from "@material-ui/core/Button";
import Paper from "@material-ui/core/Paper";
import ContentDom from "../Layout/ContentDom";
import { Job, BlankJob } from "../../models/job";
import { GetJob } from "../../services/job_service";
import { ConvertDate } from "../../helpers/DateHelper";

const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    button: {
      margin: theme.spacing(1)
    },
    paper: {
      marginTop: theme.spacing(3),
      padding: theme.spacing(3)
    }
  })
);

const Jobs: FunctionComponent<RouteComponentProps> = props => {
  const classes = useStyles({});
  const [job, setJob] = useState<Job>(BlankJob());
  const [loading, setLoading] = useState<boolean>(false);
  const params: any = props.match.params;

  useEffect(() => {
    fetchJob();
  }, [job.jobId]);

  async function fetchJob() {
    setLoading(true);
    const result = await GetJob(params.id);
    if (result) {
      setJob(result);
    }
    setLoading(false);
  }

  const content = loading ? (
    <Grid container justify="center" className="mt-24 mb-24">
      <CircularProgress color="primary" />
    </Grid>
  ) : (
    <Paper key={job.jobId} elevation={0} className={classes.paper}>
      <h6 className="primary-text text-center">{job.title}</h6>
      <h6>Salary - Benefits</h6>
      <p>{`${job.salary} - ${job.benefits}`}</p>
      <h6>Type</h6>
      <p>{job.jobType}</p>
      <h6>Location</h6>
      <p>{job.jobLocation}</p>
      <h6>Reference</h6>
      <p>{job.jobReference}</p>
      <ContentDom content={job.description}/>
      <p>Published: {ConvertDate(job.createdAt)}</p>
    </Paper>
  );

  return (
    <div>
      <Grid container justify="center" className="content-container">
        <Grid item md={8} sm={10} xs={12} className="mb-24">
          {content}
        </Grid>
        <Grid container justify="center" className="mb-24">
          <Button
            className={classes.button}
            color="primary"
            component={Link}
            to="/jobs"
          >
            Jobs
          </Button>
        </Grid>
      </Grid>
    </div>
  );
};

export default withRouter(Jobs);
