// react/src/components/Pages/Blogs.tsx
import React, { useEffect } from "react";
import { Link, withRouter } from "react-router-dom";
import { createStyles, Theme, makeStyles } from "@material-ui/core/styles";
import Grid from "@material-ui/core/Grid";
import blogsimage from "../../assets/blogs.jpg";
import Typography from "@material-ui/core/Typography";
import CircularProgress from "@material-ui/core/CircularProgress";
import Paper from "@material-ui/core/Paper";
import Blog from "../../models/blog";
import { GetAllBlogs } from "../../services/blog_service";
import { ConvertDate } from "../../helpers/DateHelper";
import { Button } from "@material-ui/core";

const useStyles = makeStyles((theme: Theme) => createStyles({
  bodyText: {
    marginBottom: theme.spacing(1)
  },
  button: {
    margin: theme.spacing(1)
  },
  paper: {
    padding: theme.spacing(2)
  }
}));

const Blogs: React.FunctionComponent = props => {
  const classes = useStyles({});
  const [blogs, setBlogs] = React.useState<Blog[]>([]);
  const [filteredBlogs, setFilteredBlogs] = React.useState<Blog[]>([]);
  const [pagedBlogs, setPagedBlogs] = React.useState<Blog[]>([]);
  const [loading, setLoading] = React.useState<boolean>(false);
  const [page, setPage] = React.useState<number>(1);
  const [blogsPages, setBlogsPages] = React.useState<number>(1);
  const [searchTerm, setSearchTerm] = React.useState<string>("");
  const blogsPerPage: number = 3;

  useEffect(() => {
    FetchBlogs();
  }, [blogs.length]);

  async function FetchBlogs() {
    setLoading(true);
    const result = await GetAllBlogs();
    if (result) {
      setBlogs(result);
    }
    onSearch();
    setLoading(false);

  }

  function onPageChange() {
    setBlogsPages(Math.ceil(filteredBlogs.length / blogsPerPage));
    setPagedBlogs(filteredBlogs.slice((page - 1) * blogsPerPage, page * blogsPerPage));
  }

  function onSearch() {
    const regex = new RegExp(`^.*${searchTerm}.*$`, "i");
    setPage(1);
    if (!searchTerm) {
      setFilteredBlogs(blogs);
    } else {
      setFilteredBlogs(blogs.filter(blog => regex.test(blog.title)));
    }
  }

  const content = loading ? (
    <Grid container justify="center" className="mt-24 mb-24">
      <CircularProgress color="primary" />
    </Grid>
  ) : (
    <>
      {filteredBlogs.map((blog: Blog) => {
        return (
          <Paper key={blog.blogId} elevation={0} className={classes.paper}>
            <Typography variant="h6" color="primary" className="text-center">
              {blog.title}
            </Typography>
            <Typography>
              {blog.description}
            </Typography>
            <Typography className="blog-short-content blog-image" dangerouslySetInnerHTML={{__html: blog.content}}>
            </Typography>
            <Typography>...</Typography>
            <Typography className="text-center">{ConvertDate(blog.createdAt)}</Typography>
            <Grid container justify="center">
              <Button className={classes.button} color="primary" component={Link} to={{ pathname: `/blog/${blog.blogId}`}}>View</Button>
            </Grid>
          </Paper>
        );
      })}
    </>
  );

  return (
    <div>
      <Grid container direction="column" justify="center">
        <Grid item xs={12}>
          <img src={blogsimage} className="header-image" alt=""/>
          <div className="header-text">Blogs</div>
        </Grid>
        <Grid container justify="center" className="content-container">
          <Grid item md={8} sm={10} xs={12} className="mb-24">
            <h2 className="content-title mb-24">News &amp; Advice Blogs</h2>
            <Typography className={classes.bodyText}>Keep up to date with the latest industry news, as well as regular activites offering recruitment and careers advice.</Typography>
          </Grid>
          <Grid item md={8} sm={10} xs={12} className="mb-24">
            {content}
          </Grid>
        </Grid>
      </Grid>
    </div>
  );
};

export default withRouter(Blogs);

// frontend/src/components/blogs/blogs.vue
<template>
  <v-layout column>
    <v-flex xs12>
      <v-img :src="require('@/assets/blogs.jpg')" class="header-image">
        <v-layout column text-xs-right justify-end fill-height class="header-padding">
          <h1 class="header-text">Blogs</h1>
        </v-layout>
      </v-img>
    </v-flex>
    <v-container fluid class="content-container">
      <v-layout row wrap justify-center>
        <v-flex md8 sm10 xs12 mb-4>
          <h2 class="content-title mb-4">News &amp; Advice Blogs</h2>
          <p>
            Keep up to date with the latest industry news, as well as regular activites offering recruitment and careers advice.
          </p>
        </v-flex>
        <v-flex md8 sm10 xs12 mb-4 v-if="!loading">
           <v-text-field v-model="searchTerm" class="mb-4" @change="onSearch" label="Search" 
            prepend-inner-icon="search" background-color="white" solo flat></v-text-field>
          <v-card flat tile>
            <v-window v-model="onboarding" vertical>
              <v-window-item :key="index" v-for="(blog, index) in filteredBlogs">
                <v-card flat >
                  <v-card-text>
                    <h3 class="title text-xs-center primary--text mb-4">{{blog.title}}</h3>
                    <p>Published: {{convertDate(blog.createdAt)}}</p>
                    <p>{{blog.description}}</p>
                    <div class="blog-short-content blog-image" v-html="blog.content"></div>
                    <p>...</p>
                  </v-card-text>
                  <v-layout justify-center>
                    <v-btn flat color="primary" class="ma-0" @click="openRoute(blog.blogId)">View</v-btn>
                  </v-layout>
                </v-card>
              </v-window-item>
            </v-window>
            <v-card-actions class="justify-space-between">
              <v-btn flat @click="prev">
                <v-icon color="primary">chevron_left</v-icon>
              </v-btn>
              <v-item-group v-model="onboarding" class="text-xs-center" mandatory v-if="$vuetify.breakpoint.smAndUp">
                <v-item v-for="(blog, index) in filteredBlogs" :key="index">
                  <v-btn slot-scope="{ active, toggle }" :input-value="active" icon @click="toggle">
                    <v-icon color="primary">fiber_manual_record</v-icon>
                  </v-btn>
                </v-item>
              </v-item-group>
              <v-btn flat @click="next">
                <v-icon color="primary">chevron_right</v-icon>
              </v-btn>
            </v-card-actions>
          </v-card>
          <v-card v-if="blogs.length < 1" flat>
            <v-card-text class="text-xs-center">
              <p>There are currently no blogs at this time :(</p>
            </v-card-text>
          </v-card>  
        </v-flex>
        <v-flex md8 sm10 xs12 mt-2 mb-5 text-xs-center v-if="loading">
           <v-progress-circular indeterminate color="primary"></v-progress-circular>
        </v-flex>
      </v-layout>
      <v-layout justify-center mb-5>
        <v-btn depressed color="primary" to="/">Home</v-btn>
      </v-layout>
    </v-container>
  </v-layout>
</template>
<script src="./blogs.ts"></script>
